name: ChargeAll
version: 1.2
author: Gwehyr
main: me.Gwehyr.chargeall.Main
description: my first real minecraft spiggot plugin it adds two commands First version to actually work

commands:
  charge:
    aliases:
    description: a command forces all creepers to spawn charged
  uncharge:
    aliases:
    description: a command that forces all creepers to spawn uncharged